#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EletricoSistema.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbEletric")]
	public partial class EletricoSistemaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_categoria(tb_categoria instance);
    partial void Updatetb_categoria(tb_categoria instance);
    partial void Deletetb_categoria(tb_categoria instance);
    partial void Inserttb_venda(tb_venda instance);
    partial void Updatetb_venda(tb_venda instance);
    partial void Deletetb_venda(tb_venda instance);
    partial void Inserttb_contas_receber(tb_contas_receber instance);
    partial void Updatetb_contas_receber(tb_contas_receber instance);
    partial void Deletetb_contas_receber(tb_contas_receber instance);
    partial void Inserttb_itens_venda(tb_itens_venda instance);
    partial void Updatetb_itens_venda(tb_itens_venda instance);
    partial void Deletetb_itens_venda(tb_itens_venda instance);
    partial void Inserttb_pessoas(tb_pessoas instance);
    partial void Updatetb_pessoas(tb_pessoas instance);
    partial void Deletetb_pessoas(tb_pessoas instance);
    partial void Inserttb_pessoas_endereco(tb_pessoas_endereco instance);
    partial void Updatetb_pessoas_endereco(tb_pessoas_endereco instance);
    partial void Deletetb_pessoas_endereco(tb_pessoas_endereco instance);
    partial void Inserttb_produto(tb_produto instance);
    partial void Updatetb_produto(tb_produto instance);
    partial void Deletetb_produto(tb_produto instance);
    partial void Inserttb_status(tb_status instance);
    partial void Updatetb_status(tb_status instance);
    partial void Deletetb_status(tb_status instance);
    partial void Inserttb_usuario(tb_usuario instance);
    partial void Updatetb_usuario(tb_usuario instance);
    partial void Deletetb_usuario(tb_usuario instance);
    #endregion
		
		public EletricoSistemaDataClassesDataContext() : 
				base(global::EletricoSistema.DataAccess.Properties.Settings.Default.dbEletricConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EletricoSistemaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EletricoSistemaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EletricoSistemaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EletricoSistemaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_categoria> tb_categoria
		{
			get
			{
				return this.GetTable<tb_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tb_venda> tb_venda
		{
			get
			{
				return this.GetTable<tb_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_contas_receber> tb_contas_receber
		{
			get
			{
				return this.GetTable<tb_contas_receber>();
			}
		}
		
		public System.Data.Linq.Table<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this.GetTable<tb_itens_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoas> tb_pessoas
		{
			get
			{
				return this.GetTable<tb_pessoas>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoas_endereco> tb_pessoas_endereco
		{
			get
			{
				return this.GetTable<tb_pessoas_endereco>();
			}
		}
		
		public System.Data.Linq.Table<tb_produto> tb_produto
		{
			get
			{
				return this.GetTable<tb_produto>();
			}
		}
		
		public System.Data.Linq.Table<tb_status> tb_status
		{
			get
			{
				return this.GetTable<tb_status>();
			}
		}
		
		public System.Data.Linq.Table<tb_usuario> tb_usuario
		{
			get
			{
				return this.GetTable<tb_usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tb_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _desc_categoria;
		
		private string _nome_categoria;
		
		private EntitySet<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Ondesc_categoriaChanging(string value);
    partial void Ondesc_categoriaChanged();
    partial void Onnome_categoriaChanging(string value);
    partial void Onnome_categoriaChanged();
    #endregion
		
		public tb_categoria()
		{
			this._tb_produto = new EntitySet<tb_produto>(new Action<tb_produto>(this.attach_tb_produto), new Action<tb_produto>(this.detach_tb_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string desc_categoria
		{
			get
			{
				return this._desc_categoria;
			}
			set
			{
				if ((this._desc_categoria != value))
				{
					this.Ondesc_categoriaChanging(value);
					this.SendPropertyChanging();
					this._desc_categoria = value;
					this.SendPropertyChanged("desc_categoria");
					this.Ondesc_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome_categoria
		{
			get
			{
				return this._nome_categoria;
			}
			set
			{
				if ((this._nome_categoria != value))
				{
					this.Onnome_categoriaChanging(value);
					this.SendPropertyChanging();
					this._nome_categoria = value;
					this.SendPropertyChanged("nome_categoria");
					this.Onnome_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_produto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tb_produto> tb_produto
		{
			get
			{
				return this._tb_produto;
			}
			set
			{
				this._tb_produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = this;
		}
		
		private void detach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class tb_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private string _valor;
		
		private string _desconto;
		
		private System.Nullable<int> _cod_venda;
		
		private System.Nullable<int> _id_pessoa_cliente;
		
		private System.Nullable<int> _id_pessoa_funcionario;
		
		private EntitySet<tb_contas_receber> _tb_contas_receber;
		
		private EntitySet<tb_itens_venda> _tb_itens_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void OndescontoChanging(string value);
    partial void OndescontoChanged();
    partial void Oncod_vendaChanging(System.Nullable<int> value);
    partial void Oncod_vendaChanged();
    partial void Onid_pessoa_clienteChanging(System.Nullable<int> value);
    partial void Onid_pessoa_clienteChanged();
    partial void Onid_pessoa_funcionarioChanging(System.Nullable<int> value);
    partial void Onid_pessoa_funcionarioChanged();
    #endregion
		
		public tb_venda()
		{
			this._tb_contas_receber = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_receber), new Action<tb_contas_receber>(this.detach_tb_contas_receber));
			this._tb_itens_venda = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_venda), new Action<tb_itens_venda>(this.detach_tb_itens_venda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OndescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("desconto");
					this.OndescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_venda", DbType="Int")]
		public System.Nullable<int> cod_venda
		{
			get
			{
				return this._cod_venda;
			}
			set
			{
				if ((this._cod_venda != value))
				{
					this.Oncod_vendaChanging(value);
					this.SendPropertyChanging();
					this._cod_venda = value;
					this.SendPropertyChanged("cod_venda");
					this.Oncod_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_cliente", DbType="Int")]
		public System.Nullable<int> id_pessoa_cliente
		{
			get
			{
				return this._id_pessoa_cliente;
			}
			set
			{
				if ((this._id_pessoa_cliente != value))
				{
					this.Onid_pessoa_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_cliente = value;
					this.SendPropertyChanged("id_pessoa_cliente");
					this.Onid_pessoa_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa_funcionario", DbType="Int")]
		public System.Nullable<int> id_pessoa_funcionario
		{
			get
			{
				return this._id_pessoa_funcionario;
			}
			set
			{
				if ((this._id_pessoa_funcionario != value))
				{
					this.Onid_pessoa_funcionarioChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa_funcionario = value;
					this.SendPropertyChanged("id_pessoa_funcionario");
					this.Onid_pessoa_funcionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_contas_receber", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_contas_receber> tb_contas_receber
		{
			get
			{
				return this._tb_contas_receber;
			}
			set
			{
				this._tb_contas_receber.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_itens_venda", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_receber(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_contas_receber(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
		
		private void attach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class tb_contas_receber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_conta;
		
		private string _data_compra;
		
		private string _data_vencimento;
		
		private string _data_pagamento;
		
		private int _id_status;
		
		private int _id_venda;
		
		private EntityRef<tb_venda> _tb_venda;
		
		private EntityRef<tb_status> _tb_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contaChanging(int value);
    partial void Onid_contaChanged();
    partial void Ondata_compraChanging(string value);
    partial void Ondata_compraChanged();
    partial void Ondata_vencimentoChanging(string value);
    partial void Ondata_vencimentoChanged();
    partial void Ondata_pagamentoChanging(string value);
    partial void Ondata_pagamentoChanged();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    #endregion
		
		public tb_contas_receber()
		{
			this._tb_venda = default(EntityRef<tb_venda>);
			this._tb_status = default(EntityRef<tb_status>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_conta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_conta
		{
			get
			{
				return this._id_conta;
			}
			set
			{
				if ((this._id_conta != value))
				{
					this.Onid_contaChanging(value);
					this.SendPropertyChanging();
					this._id_conta = value;
					this.SendPropertyChanged("id_conta");
					this.Onid_contaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_compra", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string data_compra
		{
			get
			{
				return this._data_compra;
			}
			set
			{
				if ((this._data_compra != value))
				{
					this.Ondata_compraChanging(value);
					this.SendPropertyChanging();
					this._data_compra = value;
					this.SendPropertyChanged("data_compra");
					this.Ondata_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_vencimento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string data_vencimento
		{
			get
			{
				return this._data_vencimento;
			}
			set
			{
				if ((this._data_vencimento != value))
				{
					this.Ondata_vencimentoChanging(value);
					this.SendPropertyChanging();
					this._data_vencimento = value;
					this.SendPropertyChanged("data_vencimento");
					this.Ondata_vencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_pagamento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string data_pagamento
		{
			get
			{
				return this._data_pagamento;
			}
			set
			{
				if ((this._data_pagamento != value))
				{
					this.Ondata_pagamentoChanging(value);
					this.SendPropertyChanging();
					this._data_pagamento = value;
					this.SendPropertyChanged("data_pagamento");
					this.Ondata_pagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int NOT NULL")]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					if (this._tb_status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_contas_receber.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_contas_receber.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_status", ThisKey="id_status", OtherKey="id_status", IsForeignKey=true)]
		public tb_status tb_status
		{
			get
			{
				return this._tb_status.Entity;
			}
			set
			{
				tb_status previousValue = this._tb_status.Entity;
				if (((previousValue != value) 
							|| (this._tb_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_status.Entity = null;
						previousValue.tb_contas_receber.Remove(this);
					}
					this._tb_status.Entity = value;
					if ((value != null))
					{
						value.tb_contas_receber.Add(this);
						this._id_status = value.id_status;
					}
					else
					{
						this._id_status = default(int);
					}
					this.SendPropertyChanged("tb_status");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class tb_itens_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private string _valor;
		
		private int _id_venda;
		
		private int _id_produto;
		
		private int _quantidade;
		
		private EntityRef<tb_venda> _tb_venda;
		
		private EntityRef<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    #endregion
		
		public tb_itens_venda()
		{
			this._tb_venda = default(EntityRef<tb_venda>);
			this._tb_produto = default(EntityRef<tb_produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int NOT NULL")]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._tb_produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int NOT NULL")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_itens_venda.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_itens_venda.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_produto", ThisKey="id_produto", OtherKey="id_produto", IsForeignKey=true)]
		public tb_produto tb_produto
		{
			get
			{
				return this._tb_produto.Entity;
			}
			set
			{
				tb_produto previousValue = this._tb_produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produto.Entity = null;
						previousValue.tb_itens_venda.Remove(this);
					}
					this._tb_produto.Entity = value;
					if ((value != null))
					{
						value.tb_itens_venda.Add(this);
						this._id_produto = value.id_produto;
					}
					else
					{
						this._id_produto = default(int);
					}
					this.SendPropertyChanged("tb_produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoas")]
	public partial class tb_pessoas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pessoas;
		
		private System.DateTime _data_nascimento;
		
		private string _CPF_CNPJ;
		
		private System.DateTime _data_cadastro;
		
		private string _situacao_cadastro;
		
		private string _tipo_cadastro;
		
		private string _cargo;
		
		private string _sexo;
		
		private string _setor;
		
		private string _nome_pessoa;
		
		private string _contato;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _data_admissao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pessoasChanging(int value);
    partial void Onid_pessoasChanged();
    partial void Ondata_nascimentoChanging(System.DateTime value);
    partial void Ondata_nascimentoChanged();
    partial void OnCPF_CNPJChanging(string value);
    partial void OnCPF_CNPJChanged();
    partial void Ondata_cadastroChanging(System.DateTime value);
    partial void Ondata_cadastroChanged();
    partial void Onsituacao_cadastroChanging(string value);
    partial void Onsituacao_cadastroChanged();
    partial void Ontipo_cadastroChanging(string value);
    partial void Ontipo_cadastroChanged();
    partial void OncargoChanging(string value);
    partial void OncargoChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnsetorChanging(string value);
    partial void OnsetorChanged();
    partial void Onnome_pessoaChanging(string value);
    partial void Onnome_pessoaChanged();
    partial void OncontatoChanging(string value);
    partial void OncontatoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondata_admissaoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_admissaoChanged();
    #endregion
		
		public tb_pessoas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pessoas
		{
			get
			{
				return this._id_pessoas;
			}
			set
			{
				if ((this._id_pessoas != value))
				{
					this.Onid_pessoasChanging(value);
					this.SendPropertyChanging();
					this._id_pessoas = value;
					this.SendPropertyChanged("id_pessoas");
					this.Onid_pessoasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nascimento", DbType="DateTime NOT NULL")]
		public System.DateTime data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				if ((this._data_nascimento != value))
				{
					this.Ondata_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nascimento = value;
					this.SendPropertyChanged("data_nascimento");
					this.Ondata_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF_CNPJ", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CPF_CNPJ
		{
			get
			{
				return this._CPF_CNPJ;
			}
			set
			{
				if ((this._CPF_CNPJ != value))
				{
					this.OnCPF_CNPJChanging(value);
					this.SendPropertyChanging();
					this._CPF_CNPJ = value;
					this.SendPropertyChanged("CPF_CNPJ");
					this.OnCPF_CNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_cadastro", DbType="DateTime NOT NULL")]
		public System.DateTime data_cadastro
		{
			get
			{
				return this._data_cadastro;
			}
			set
			{
				if ((this._data_cadastro != value))
				{
					this.Ondata_cadastroChanging(value);
					this.SendPropertyChanging();
					this._data_cadastro = value;
					this.SendPropertyChanged("data_cadastro");
					this.Ondata_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacao_cadastro", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string situacao_cadastro
		{
			get
			{
				return this._situacao_cadastro;
			}
			set
			{
				if ((this._situacao_cadastro != value))
				{
					this.Onsituacao_cadastroChanging(value);
					this.SendPropertyChanging();
					this._situacao_cadastro = value;
					this.SendPropertyChanged("situacao_cadastro");
					this.Onsituacao_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_cadastro", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string tipo_cadastro
		{
			get
			{
				return this._tipo_cadastro;
			}
			set
			{
				if ((this._tipo_cadastro != value))
				{
					this.Ontipo_cadastroChanging(value);
					this.SendPropertyChanging();
					this._tipo_cadastro = value;
					this.SendPropertyChanged("tipo_cadastro");
					this.Ontipo_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(50)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this.OncargoChanging(value);
					this.SendPropertyChanging();
					this._cargo = value;
					this.SendPropertyChanged("cargo");
					this.OncargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(12)")]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setor", DbType="VarChar(50)")]
		public string setor
		{
			get
			{
				return this._setor;
			}
			set
			{
				if ((this._setor != value))
				{
					this.OnsetorChanging(value);
					this.SendPropertyChanging();
					this._setor = value;
					this.SendPropertyChanged("setor");
					this.OnsetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_pessoa", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string nome_pessoa
		{
			get
			{
				return this._nome_pessoa;
			}
			set
			{
				if ((this._nome_pessoa != value))
				{
					this.Onnome_pessoaChanging(value);
					this.SendPropertyChanging();
					this._nome_pessoa = value;
					this.SendPropertyChanged("nome_pessoa");
					this.Onnome_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contato", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string contato
		{
			get
			{
				return this._contato;
			}
			set
			{
				if ((this._contato != value))
				{
					this.OncontatoChanging(value);
					this.SendPropertyChanging();
					this._contato = value;
					this.SendPropertyChanged("contato");
					this.OncontatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_admissao", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_admissao
		{
			get
			{
				return this._data_admissao;
			}
			set
			{
				if ((this._data_admissao != value))
				{
					this.Ondata_admissaoChanging(value);
					this.SendPropertyChanging();
					this._data_admissao = value;
					this.SendPropertyChanged("data_admissao");
					this.Ondata_admissaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoas_endereco")]
	public partial class tb_pessoas_endereco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_endereco;
		
		private string _tp_endereco1;
		
		private string _endereco1;
		
		private int _id_pessoas;
		
		private string _tp_endereco2;
		
		private string _endereco2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_enderecoChanging(int value);
    partial void Onid_enderecoChanged();
    partial void Ontp_endereco1Changing(string value);
    partial void Ontp_endereco1Changed();
    partial void Onendereco1Changing(string value);
    partial void Onendereco1Changed();
    partial void Onid_pessoasChanging(int value);
    partial void Onid_pessoasChanged();
    partial void Ontp_endereco2Changing(string value);
    partial void Ontp_endereco2Changed();
    partial void Onendereco2Changing(string value);
    partial void Onendereco2Changed();
    #endregion
		
		public tb_pessoas_endereco()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_endereco", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_endereco
		{
			get
			{
				return this._id_endereco;
			}
			set
			{
				if ((this._id_endereco != value))
				{
					this.Onid_enderecoChanging(value);
					this.SendPropertyChanging();
					this._id_endereco = value;
					this.SendPropertyChanged("id_endereco");
					this.Onid_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tp_endereco1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tp_endereco1
		{
			get
			{
				return this._tp_endereco1;
			}
			set
			{
				if ((this._tp_endereco1 != value))
				{
					this.Ontp_endereco1Changing(value);
					this.SendPropertyChanging();
					this._tp_endereco1 = value;
					this.SendPropertyChanged("tp_endereco1");
					this.Ontp_endereco1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string endereco1
		{
			get
			{
				return this._endereco1;
			}
			set
			{
				if ((this._endereco1 != value))
				{
					this.Onendereco1Changing(value);
					this.SendPropertyChanging();
					this._endereco1 = value;
					this.SendPropertyChanged("endereco1");
					this.Onendereco1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoas", DbType="Int NOT NULL")]
		public int id_pessoas
		{
			get
			{
				return this._id_pessoas;
			}
			set
			{
				if ((this._id_pessoas != value))
				{
					this.Onid_pessoasChanging(value);
					this.SendPropertyChanging();
					this._id_pessoas = value;
					this.SendPropertyChanged("id_pessoas");
					this.Onid_pessoasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tp_endereco2", DbType="VarChar(50)")]
		public string tp_endereco2
		{
			get
			{
				return this._tp_endereco2;
			}
			set
			{
				if ((this._tp_endereco2 != value))
				{
					this.Ontp_endereco2Changing(value);
					this.SendPropertyChanging();
					this._tp_endereco2 = value;
					this.SendPropertyChanged("tp_endereco2");
					this.Ontp_endereco2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco2", DbType="VarChar(50)")]
		public string endereco2
		{
			get
			{
				return this._endereco2;
			}
			set
			{
				if ((this._endereco2 != value))
				{
					this.Onendereco2Changing(value);
					this.SendPropertyChanging();
					this._endereco2 = value;
					this.SendPropertyChanged("endereco2");
					this.Onendereco2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tb_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _desc_produto;
		
		private string _valor;
		
		private int _id_categoria;
		
		private string _nome;
		
		private int _quantidade;
		
		private EntitySet<tb_itens_venda> _tb_itens_venda;
		
		private EntityRef<tb_categoria> _tb_categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Ondesc_produtoChanging(string value);
    partial void Ondesc_produtoChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    #endregion
		
		public tb_produto()
		{
			this._tb_itens_venda = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_venda), new Action<tb_itens_venda>(this.detach_tb_itens_venda));
			this._tb_categoria = default(EntityRef<tb_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_produto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string desc_produto
		{
			get
			{
				return this._desc_produto;
			}
			set
			{
				if ((this._desc_produto != value))
				{
					this.Ondesc_produtoChanging(value);
					this.SendPropertyChanging();
					this._desc_produto = value;
					this.SendPropertyChanged("desc_produto");
					this.Ondesc_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tb_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int NOT NULL")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_itens_venda", ThisKey="id_produto", OtherKey="id_produto")]
		public EntitySet<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tb_categoria tb_categoria
		{
			get
			{
				return this._tb_categoria.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria.Entity = null;
						previousValue.tb_produto.Remove(this);
					}
					this._tb_categoria.Entity = value;
					if ((value != null))
					{
						value.tb_produto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("tb_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = this;
		}
		
		private void detach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status")]
	public partial class tb_status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status;
		
		private EntitySet<tb_contas_receber> _tb_contas_receber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tb_status()
		{
			this._tb_contas_receber = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_receber), new Action<tb_contas_receber>(this.detach_tb_contas_receber));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_contas_receber", ThisKey="id_status", OtherKey="id_status")]
		public EntitySet<tb_contas_receber> tb_contas_receber
		{
			get
			{
				return this._tb_contas_receber;
			}
			set
			{
				this._tb_contas_receber.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_receber(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status = this;
		}
		
		private void detach_tb_contas_receber(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tb_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _id_user;
		
		private int _id_pessoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_pessoasChanging(int value);
    partial void Onid_pessoasChanged();
    #endregion
		
		public tb_usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoas", DbType="Int NOT NULL")]
		public int id_pessoas
		{
			get
			{
				return this._id_pessoas;
			}
			set
			{
				if ((this._id_pessoas != value))
				{
					this.Onid_pessoasChanging(value);
					this.SendPropertyChanging();
					this._id_pessoas = value;
					this.SendPropertyChanged("id_pessoas");
					this.Onid_pessoasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
